### PR TITLE
PHARYNX and WORM analysis types for fluorescent image processing

### PR DESCRIPTION
**Pull request by ljschumacher**
could you merge this but reject my local changes to MWTracker/processing/batchProcHelperFunc.py ?

### CODE REVIEW

**Comment by ver228** [comment]
I cannot accept the deletion of VID_SUBSAMPLE. I need that step. It is possible to define the steps to be done in the command line using `processMultipleFiles.py` and specifying them in `--analysis_checkpoints`. I plan to incorporate this into the GUI later on.

**Comment by ljschumacher** [comment]
Yes, I realised that, hence I mentioned it in the comment for the pull request - sorry if that was not visible

Can you accept the rest and just reject those changes relating to VID_SUBSAMPLE for now?

**Comment by ver228** [comment]
Sorry, I just read the first msg. I cannot accept changes individually. You have to alter the local changes before merging.

**Comment by ljschumacher** [comment]
I was familiar with how to skip the vid_subsample in the command line for tracking, is this now also possible for the compression step?

**Comment by ljschumacher** [comment]
I corrected my local changes so they should now be compatible

**Pull request merged**
